export const SELECT_CHECKED = "SELECT_CHECKED";
export const SELECT_UNCHECKED = "SELECT_UNCHECKED";
export const ADD_CHECKED = "ADD_CHECKED";
export const ALL_CHECKED = "ALL_CHECKED"
export const REMOVE_CHECKED = "REMOVE_CHECKED"